version: "3.8"

services:
  app:
    build:
      context: .
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: "src"
        target: "/app/src"
    depends_on:
      - queue
    command: python main.py

  queue:
    image: roribio16/alpine-sqs
    ports:
      - 9324:9324
      - 9325:9325